name: Deploy to Azure App Service

on:
  push: 
    branches: 
      - main

jobs: 
  login-to-azure:
    runs-on: windows-latest
    steps:
      - name: Azure login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: login to ACR using updated access token
        run: echo ${{ secrets.ACR_ACCESS_TOKEN }} | docker login test98acr.azurecr.io --username _ --password-stdin
      - name: set context
        uses: azure/aks-set-context@v3
        with:
          resource-group: 'Kuberneetes'
          cluster-name: 'demo'
      - name: deploy
        uses: Azure/k8s-deploy@v1
        with:
          manifests: |
            nodedemo.yml

      
