name: Deploy to Azure App Service

on:
  push: 
    branches: 
      - main

jobs: 
  login-to-azure:
    runs-on: windows-latest
    steps:
      - name: Azure login
        uses: azure/login@v2
        with:
          auth-type: IDENTITY          
          tenant-id: 7359f896-71e2-4dae-b8a3-15cdf97f2f10
          subscription-id: 5d0e38a3-8ba1-4308-81f6-3a76788ecdf7
          enable-AzPSSession: true
      
