name: Deploy to Azure App Service

on:
  push: 
    branches: 
      - main

jobs: 
  build-dockerfile-and-deploy-image-to-dockerhub:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v3
      - name: Login to ACR
        uses: azure/docker-login@v1
        with:
          login-server: test98acr.azurecr.io
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}
      - name: Build Docker Image from Dockerfile
        run: docker build -t demo_image .
      - name: Push Image to docker
        run: docker push test98acr.azurecr.io/demo_image:v1